#!/usr/bin/python3
'''Minimum Operations python3 challenge'''


def minOperations(n):
    '''Calculates the fewest number of
    operations needed to result in exactly n H
    characters in this file.
    
    Returns:
        Integer : if n is impossible to achieve, return 0
    '''
    if n <= 1:
        return 0  # No operations needed for 0 or 1

    pasted_chars = 1  # Start with one character
    clipboard = 0  # Nothing is copied yet
    counter = 0  # Count operations

    while pasted_chars < n:
        if clipboard == 0:  # First operation: Copy All
            clipboard = pasted_chars
            counter += 1
        elif pasted_chars == 1:  # If only one character, we can only paste
            pasted_chars += clipboard
            counter += 1
        else:
            if (n - pasted_chars) % pasted_chars == 0:  # If divisible
                clipboard = pasted_chars
                pasted_chars += clipboard
                counter += 2  # Copy All + Paste
            else:  # If not divisible
                pasted_chars += clipboard
                counter += 1  # Just Paste

    return counter if pasted_chars == n else 0

